#!/usr/bin/env python3
"""Build the theme's line-icon set as CSS custom properties (data-URI SVGs).

Each icon `name` gives two classes:
  .ico-<name>   sets --ico (white stroke, for gradient tiles) and --ico-ink (navy stroke)
Use together with .sr-icon (tile above content) or .sr-chip-icon (small inline icon).
Output: wp-content/themes/shriram-college/assets/css/icons.css
"""
import os
from urllib.parse import quote

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "wp-content", "themes", "shriram-college", "assets", "css", "icons.css")


def circle(cx, cy, r):
    return f"M{cx - r} {cy}a{r} {r} 0 1 0 {2 * r} 0a{r} {r} 0 1 0 {-2 * r} 0"


ICONS = {
    "nurse": ["M4 11c0-3.3 3.6-6 8-6s8 2.7 8 6l-2 4H6z", "M12 7.5v4M10 9.5h4", "M6 19h12"],
    "stethoscope": ["M6 3v5a4 4 0 0 0 8 0V3", "M10 12v3a5 5 0 0 0 10 0v-2", circle(20, 11, 2)],
    "pulse": ["M3 12h4l2-5 4 10 2-5h6"],
    "hospital": ["M4 21V8l8-5 8 5v13", "M9 21v-4h6v4", "M12 8v5M9.5 10.5h5", "M2 21h20"],
    "book": ["M4 19V5a2 2 0 0 1 2-2h14v14H6a2 2 0 0 0-2 2 2 2 0 0 0 2 2h14", "M8 7h8"],
    "flask": ["M9 3h6", "M10 3v6l-5.5 9.5A2 2 0 0 0 6.2 21h11.6a2 2 0 0 0 1.7-2.5L14 9V3", "M7.5 15h9"],
    "microscope": ["M6 21h12", "M9 18h7", "M14 11a5 5 0 0 1 0 7", "M10 3l3 1.2-2.4 6.3-3-1.2z", "M9.5 10.5 8 14"],
    "users": ["M16 20v-1a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v1", circle(9, 8, 3.5), "M22 20v-1a4 4 0 0 0-3-3.8", "M16 4.3a3.5 3.5 0 0 1 0 7"],
    "bed": ["M3 19V6", "M3 14h18v5", "M21 14v-3a3 3 0 0 0-3-3h-7v6", circle(7, 10.5, 1.8)],
    "bus": ["M5 3h14a2 2 0 0 1 2 2v12H3V5a2 2 0 0 1 2-2z", "M3 11h18", "M7 17v3M17 17v3", "M7 14h.01M17 14h.01"],
    "wifi": ["M2 9a15 15 0 0 1 20 0", "M5 12.5a10 10 0 0 1 14 0", "M8.5 16a5 5 0 0 1 7 0", "M12 19.5h.01"],
    "dumbbell": ["M6 7v10M18 7v10M3 10v4M21 10v4M6 12h12"],
    "graduation": ["M2 9l10-5 10 5-10 5z", "M6 11v5c3 2.5 9 2.5 12 0v-5", "M22 9v5"],
    "shield": ["M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z", "M8.5 12l2.5 2.5 4.5-5"],
    "award": [circle(12, 9, 6), "M8.5 14l-1.5 7 5-3 5 3-1.5-7"],
    "clipboard": ["M9 3h6v3H9z", "M9 4.5H6a1 1 0 0 0-1 1V20a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V5.5a1 1 0 0 0-1-1h-3", "M9 12h6M9 16h4"],
    "home": ["M3 11l9-7 9 7", "M5 10v10h14V10", "M10 20v-5h4v5"],
    "utensils": ["M5 3v5a2 2 0 0 0 4 0V3", "M7 3v18", "M17 21V3c-2 1-3 4-3 7h3"],
    "stage": ["M3 4h18", "M4 4v10h16V4", "M12 14v4", "M8 21l4-3 4 3"],
    "monitor": ["M3 4h18v12H3z", "M8 20h8M12 16v4"],
    "heart": ["M12 20s-7-4.5-7-10a4 4 0 0 1 7-2.6A4 4 0 0 1 19 10c0 5.5-7 10-7 10z"],
    "syringe": ["M18 2l4 4", "M20 4l-9.5 9.5", "M14 6l4 4", "M13.5 7.5 5 16l-1 4 4-1 8.5-8.5", "M8 12l1.5 1.5M10 10l1.5 1.5"],
    "pin": ["M12 21s-7-6.5-7-12a7 7 0 0 1 14 0c0 5.5-7 12-7 12z", circle(12, 9, 2.5)],
    "phone": ["M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2"],
    "mail": ["M3 5h18v14H3z", "M3 6l9 7 9-7"],
    "train": ["M6 3h12a2 2 0 0 1 2 2v10a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V5a2 2 0 0 1 2-2z", "M4 11h16", "M8 21l2-3M16 21l-2-3", "M8 14.5h.01M16 14.5h.01"],
    "clock": [circle(12, 12, 9), "M12 7v5l3 2"],
    "file": ["M14 3H6v18h12V7z", "M14 3v4h4", "M9 13h6M9 17h6"],
    "lamp": ["M4 15h13a3 3 0 0 0 0-6h-2", "M6 15c0-3 2.5-5 6-5h3", "M8 19h9", "M12 2.5c1.5 2 2 3 2 4a2 2 0 0 1-4 0c0-1 .5-2 2-4z"],
    "firstaid": ["M4 7h16v13H4z", "M9 7V4h6v3", "M12 10.5v6M9 13.5h6"],
    "globe": [circle(12, 12, 9), "M3 12h18", "M12 3a14 14 0 0 1 0 18a14 14 0 0 1 0-18"],
    "rupee": ["M7 4h10M7 8.5h10", "M7 4h3a4.5 4.5 0 0 1 0 9H7l8 8"],
    "target": [circle(12, 12, 9), circle(12, 12, 5), "M12 12h.01"],
    "eye": ["M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z", circle(12, 12, 3)],
    "hands": ["M11 14l-2 2a2 2 0 0 1-3 0l-3-3", "M13 10l2-2a2 2 0 0 1 3 0l3 3", "M7 12l5-5 4 4-5 5z"],
    "calendar": ["M4 5h16v16H4z", "M4 10h16", "M9 3v4M15 3v4"],
    "idcard": ["M3 5h18v14H3z", circle(9, 11, 2), "M6 16c.5-1.5 1.7-2 3-2s2.5.5 3 2", "M14 10h4M14 14h3"],
    "search": [circle(11, 11, 7), "M20 20l-4-4"],
    "check": ["M5 12l5 5L20 7"],
    "arrow": ["M5 12h14", "M13 6l6 6-6 6"],
    "tree": ["M12 22v-6", "M12 2 5 12h4l-3 4h12l-3-4h4z"],
    "camera": ["M3 7h4l2-3h6l2 3h4v13H3z", circle(12, 13, 4)],
}


def svg(paths, stroke):
    d = "".join(f'<path d="{p}"/>' for p in paths)
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="{stroke}" '
            f'stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{d}</svg>')


def uri(s):
    return 'url("data:image/svg+xml,' + quote(s, safe="/:=,; ") + '")'


lines = ["/* Generated by tools/build_icons.py. Do not edit by hand. */"]
for name, paths in ICONS.items():
    lines.append(f".ico-{name}{{--ico:{uri(svg(paths, '#ffffff'))};--ico-ink:{uri(svg(paths, '#0E4A6E'))}}}")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"{len(ICONS)} icons -> {OUT}")
