"""Hindi text for the site pages: English text (exactly as written in build_content.py) -> Hindi.

build_content.py stops with a list of any English string missing here, so when you add or change
English text there, add the Hindi version here too. Keep the HTML tags and links the same; links
like href="/about/" are pointed at the Hindi pages (/hi/about/) automatically.

Style: plain, everyday Hindi as used by Haryana health-education notices. Regulator and exam
acronyms (INC, HNRC, UHSR, DMER, CET, NEET) stay in Latin letters as students see them on forms.
"""

HI = {
    # ------------------------------------------------------------ shared: names, bodies, courses
    "B.Sc Nursing": "बी.एससी. नर्सिंग",
    "Post Basic B.Sc Nursing": "पोस्ट बेसिक बी.एससी. नर्सिंग",
    "B.Sc Paramedical Science": "बी.एससी. पैरामेडिकल साइंस",
    "B.Sc Paramedical": "बी.एससी. पैरामेडिकल",
    "GNM": "जीएनएम",
    "ANM": "एएनएम",
    "GNM – General Nursing &amp; Midwifery": "जीएनएम – जनरल नर्सिंग एवं मिडवाइफरी",
    "ANM – Auxiliary Nurse Midwifery": "एएनएम – ऑक्ज़िलरी नर्स मिडवाइफरी",
    "INC Approved": "INC द्वारा अनुमोदित",
    "HNRC Recognised": "HNRC से मान्यता प्राप्त",
    "Pt. B.D. Sharma UHS, Rohtak": "पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक",
    "Pt. B.D. Sharma University of Health Sciences, Rohtak": "पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक",
    "Affiliated to Pt. B.D. Sharma UHS, Rohtak": "पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक से संबद्ध",
    "Haryana Nurses &amp; Midwives Council": "हरियाणा नर्सेज़ एवं मिडवाइव्स काउंसिल",
    "Indian Nursing Council, New Delhi": "भारतीय नर्सिंग परिषद, नई दिल्ली",
    "Indian Nursing Council; Haryana Nurses &amp; Midwives Council": "भारतीय नर्सिंग परिषद; हरियाणा नर्सेज़ एवं मिडवाइव्स काउंसिल",
    "Shri Ram Krishan Param Hans Shiksha Parishad": "श्री राम कृष्ण परम हंस शिक्षा परिषद",
    "VPO Digrota, Nangal Mala Road, Tehsil Satnali, Distt. Mahendragarh, Haryana – 123024":
        "गाँव व डाकघर डिगरोता, नांगल माला रोड, तहसील सतनाली, जिला महेंद्रगढ़, हरियाणा – 123024",
    "INC &amp; HNRC": "INC एवं HNRC",
    "HNRC &amp; INC": "HNRC एवं INC",
    "UHSR counselling": "UHSR काउंसलिंग",
    "Full time": "पूर्णकालिक",
    "Undergraduate degree": "स्नातक डिग्री",
    "Diploma": "डिप्लोमा",
    "Merit": "मेरिट",
    "Level": "स्तर",
    "Duration": "अवधि",
    "Seats": "सीटें",
    "Approval": "अनुमोदन",
    "Affiliation": "संबद्धता",
    "Admission": "प्रवेश",
    "Eligibility": "पात्रता",
    "Hospital": "अस्पताल",
    "Home": "होम",
    "Courses": "पाठ्यक्रम",
    "Admissions": "प्रवेश",
    "Admission process": "प्रवेश प्रक्रिया",
    "Admission Process": "प्रवेश प्रक्रिया",
    "Fee structure": "शुल्क संरचना",
    "Fee Structure": "शुल्क संरचना",
    "Enquire now": "पूछताछ करें",
    "Programmes": "पाठ्यक्रम",
    "Principal": "प्रधानाचार्य",
    "Faculty": "संकाय",
    "Gallery": "गैलरी",
    "Campus": "परिसर",
    "Notices": "सूचनाएँ",
    "Contact Us": "संपर्क करें",
    "About the College": "कॉलेज के बारे में",
    "Approvals &amp; Affiliations": "मान्यता एवं संबद्धता",
    "Campus &amp; Facilities": "परिसर एवं सुविधाएँ",
    "Mandatory Disclosure": "अनिवार्य प्रकटीकरण",
    "Separate hostels for girls and boys": "छात्राओं और छात्रों के लिए अलग-अलग छात्रावास",
    "Own 100-bed hospital": "अपना 100 बिस्तरों वाला अस्पताल",
    "Community health nursing": "सामुदायिक स्वास्थ्य नर्सिंग",
    "Child health nursing": "शिशु स्वास्थ्य नर्सिंग",
    "Higher studies: M.Sc Nursing": "उच्च शिक्षा: एम.एससी. नर्सिंग",
    "Qualification": "योग्यता",

    # ------------------------------------------------------------ course cards and filter
    "Filter programmes": "पाठ्यक्रम छाँटें",
    "All programmes": "सभी पाठ्यक्रम",
    "Degrees": "डिग्री",
    "Diplomas": "डिप्लोमा",
    "Degree programme": "डिग्री पाठ्यक्रम",
    "Diploma programme": "डिप्लोमा पाठ्यक्रम",
    "2 years": "2 वर्ष",
    "3 years": "3 वर्ष",
    "4 years": "4 वर्ष",
    "30 seats": "30 सीटें",
    "40 seats": "40 सीटें",
    "50 seats": "50 सीटें",
    "Seats as approved": "स्वीकृत सीटों के अनुसार",
    "A four-year professional degree that builds a strong foundation in nursing science, anatomy and direct patient care, with extensive hospital practice.":
        "चार वर्ष की व्यावसायिक डिग्री, जो नर्सिंग विज्ञान, शरीर रचना और रोगी की प्रत्यक्ष देखभाल की मज़बूत नींव रखती है, साथ में अस्पताल में व्यापक अभ्यास।",
    "A two-year degree for registered GNM nurses who want to upgrade to a B.Sc qualification and take on greater clinical and leadership roles.":
        "पंजीकृत जीएनएम नर्सों के लिए दो वर्ष की डिग्री, जो बी.एससी. योग्यता हासिल कर बड़ी क्लिनिकल और नेतृत्व भूमिकाएँ निभाना चाहती हैं।",
    "A three-year allied-health degree awarded by Pt. B.D. Sharma UHS, Rohtak, preparing technologists for hospital and diagnostic settings.":
        "पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक द्वारा प्रदान की जाने वाली तीन वर्ष की एलाइड हेल्थ डिग्री, जो अस्पतालों और जाँच केंद्रों के लिए टेक्नोलॉजिस्ट तैयार करती है।",
    "A diploma programme in general nursing and midwifery, leading to registration as a nurse and midwife with the state council.":
        "जनरल नर्सिंग और मिडवाइफरी का डिप्लोमा पाठ्यक्रम, जिसके बाद राज्य परिषद में नर्स और मिडवाइफ के रूप में पंजीकरण होता है।",
    "A two-year diploma that trains community health workers in maternal and child health, first aid and primary care.":
        "दो वर्ष का डिप्लोमा, जो सामुदायिक स्वास्थ्य कार्यकर्ताओं को मातृ एवं शिशु स्वास्थ्य, प्राथमिक उपचार और प्राथमिक देखभाल का प्रशिक्षण देता है।",
    '<a href="/courses/bsc-nursing/">View course details</a>': '<a href="/courses/bsc-nursing/">पाठ्यक्रम का पूरा विवरण</a>',
    '<a href="/courses/post-basic-bsc-nursing/">View course details</a>': '<a href="/courses/post-basic-bsc-nursing/">पाठ्यक्रम का पूरा विवरण</a>',
    '<a href="/courses/bsc-paramedical-science/">View course details</a>': '<a href="/courses/bsc-paramedical-science/">पाठ्यक्रम का पूरा विवरण</a>',
    '<a href="/courses/gnm/">View course details</a>': '<a href="/courses/gnm/">पाठ्यक्रम का पूरा विवरण</a>',
    '<a href="/courses/anm/">View course details</a>': '<a href="/courses/anm/">पाठ्यक्रम का पूरा विवरण</a>',

    # ------------------------------------------------------------ photo descriptions and credits
    "Shri Ram College campus buildings and lawns, Digrota": "श्री राम कॉलेज परिसर के भवन और लॉन, डिगरोता",
    "Main academic building of Shri Ram College, Digrota": "श्री राम कॉलेज, डिगरोता का मुख्य शैक्षणिक भवन",
    "Shri Ram Hospital building on the college campus": "कॉलेज परिसर में श्री राम अस्पताल का भवन",
    "Main gate of Shri Ram Medical College & Hospital": "श्री राम मेडिकल कॉलेज एवं अस्पताल का मुख्य द्वार",
    "Entrance gate of Shri Ram Medical College & Hospital": "श्री राम मेडिकल कॉलेज एवं अस्पताल का प्रवेश द्वार",
    "College building at dusk": "शाम के समय कॉलेज भवन",
    "Hospital ward with beds and screens": "बिस्तरों और पर्दों वाला अस्पताल वार्ड",
    "Demonstration ward with hospital beds": "अस्पताल बिस्तरों वाला डेमोंस्ट्रेशन वार्ड",
    "Emergency department entrance in the college hospital": "कॉलेज अस्पताल में आपातकालीन विभाग का प्रवेश द्वार",
    "Examination room with delivery table": "डिलीवरी टेबल वाला जाँच कक्ष",
    "Nursing foundation lab with beds and wheelchair": "बिस्तरों और व्हीलचेयर वाली नर्सिंग फ़ाउंडेशन लैब",
    "Students practising bed making in the nursing skill lab": "नर्सिंग स्किल लैब में बेड मेकिंग का अभ्यास करते विद्यार्थी",
    "Faculty and visitors during a ward inspection": "वार्ड निरीक्षण के दौरान शिक्षक और आगंतुक",
    "College library reading hall": "कॉलेज पुस्तकालय का वाचन कक्ष",
    "Spacious library hall with reading tables": "पढ़ने की मेज़ों वाला विशाल पुस्तकालय हॉल",
    "Nursing students attending a lecture": "व्याख्यान में उपस्थित नर्सिंग विद्यार्थी",
    "Lecture hall with students": "विद्यार्थियों के साथ व्याख्यान कक्ष",
    "Entrance to the nutrition lab": "पोषण प्रयोगशाला का प्रवेश द्वार",
    "Visitors in the laboratory with herbal specimen charts": "हर्बल नमूना चार्टों वाली प्रयोगशाला में आगंतुक",
    "Anatomy models and specimens in the lab": "प्रयोगशाला में शरीर रचना के मॉडल और नमूने",
    "Obstetric models showing stages of pregnancy": "गर्भावस्था के चरण दिखाते प्रसूति मॉडल",
    "Human anatomy mannequin": "मानव शरीर रचना का पुतला",
    "Patient simulator on a bed in the skill lab": "स्किल लैब में बिस्तर पर रोगी सिम्युलेटर",
    "Pre-clinical lab hall with charts and models": "चार्ट और मॉडलों वाला प्री-क्लिनिकल लैब हॉल",
    "Nursing students in uniform, group photo": "वर्दी में नर्सिंग विद्यार्थियों की सामूहिक फ़ोटो",
    "A batch of nursing students on the college lawn": "कॉलेज लॉन पर नर्सिंग विद्यार्थियों का एक बैच",
    "Students gathered on the campus lawn": "परिसर के लॉन में एकत्रित विद्यार्थी",
    "Stage decorated for a college ceremony": "कॉलेज समारोह के लिए सजा मंच",
    "Students at a college cultural event": "कॉलेज के सांस्कृतिक कार्यक्रम में विद्यार्थी",
    "Farewell 2K24 celebration": "विदाई समारोह 2024",
    "Photo: AMRIT SINGH via Google Maps": "फ़ोटो: AMRIT SINGH, गूगल मैप्स के माध्यम से",
    "Photo: DS KNOWLEDGE via Google Maps": "फ़ोटो: DS KNOWLEDGE, गूगल मैप्स के माध्यम से",
    "Photo: Yogendra Kumar via Google Maps": "फ़ोटो: योगेंद्र कुमार, गूगल मैप्स के माध्यम से",
    "Illustration of the college hospital with a heartbeat line": "धड़कन की रेखा के साथ कॉलेज अस्पताल का चित्र",

    # ------------------------------------------------------------ HOME
    "New notices will appear here.": "नई सूचनाएँ यहाँ दिखाई देंगी।",
    "Digrota · Satnali · Mahendragarh · Haryana": "डिगरोता · सतनाली · महेंद्रगढ़ · हरियाणा",
    "Shaping skilled, <em>compassionate</em> nurses &amp; healthcare professionals":
        "कुशल और <em>संवेदनशील</em> नर्सें व स्वास्थ्य पेशेवर तैयार करना",
    "Nursing and paramedical programmes approved by the Indian Nursing Council and affiliated to Pt. B.D. Sharma University of Health Sciences, Rohtak, with hands-on clinical training at our own 100-bed hospital.":
        "भारतीय नर्सिंग परिषद से अनुमोदित और पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक से संबद्ध नर्सिंग एवं पैरामेडिकल पाठ्यक्रम, हमारे अपने 100 बिस्तरों वाले अस्पताल में व्यावहारिक क्लिनिकल प्रशिक्षण के साथ।",
    "Apply for Admission": "प्रवेश के लिए आवेदन करें",
    "Explore Courses": "पाठ्यक्रम देखें",
    "✓ INC Approved": "✓ INC द्वारा अनुमोदित",
    "✓ HNRC Recognised": "✓ HNRC से मान्यता प्राप्त",
    "✓ UHSR Rohtak Affiliated": "✓ UHSR रोहतक से संबद्ध",
    "<strong>100-bed</strong>attached hospital": "<strong>100 बिस्तरों</strong>का संबद्ध अस्पताल",
    "<strong>5</strong>programmes": "<strong>5</strong>पाठ्यक्रम",
    "Bed attached hospital": "बिस्तरों वाला संबद्ध अस्पताल",
    "Nursing &amp; paramedical programmes": "नर्सिंग एवं पैरामेडिकल पाठ्यक्रम",
    "Approved seats every year": "हर वर्ष स्वीकृत सीटें",
    "Separate hostels for girls &amp; boys": "छात्राओं व छात्रों के लिए अलग छात्रावास",
    "Since": "स्थापना",
    "A trusted name in nursing education in Mahendragarh district.": "महेंद्रगढ़ ज़िले में नर्सिंग शिक्षा का एक भरोसेमंद नाम।",
    "Approved by the Indian Nursing Council": "भारतीय नर्सिंग परिषद द्वारा अनुमोदित",
    "Recognised by the Haryana Nurses &amp; Midwives Council": "हरियाणा नर्सेज़ एवं मिडवाइव्स काउंसिल से मान्यता प्राप्त",
    "Private, co-educational institution": "निजी, सह-शिक्षा संस्थान",
    "About the college": "कॉलेज परिचय",
    "Quality nursing education in the heart of rural Haryana": "ग्रामीण हरियाणा के बीच गुणवत्तापूर्ण नर्सिंग शिक्षा",
    "Shri Ram College of Medical Science &amp; Research at Digrota, Mahendragarh, runs <strong>Shri Ram College of Nursing</strong> and <strong>Shri Ram School of Nursing</strong>, offering degree and diploma programmes in nursing and allied health.":
        "डिगरोता, महेंद्रगढ़ स्थित श्री राम कॉलेज ऑफ़ मेडिकल साइंस एंड रिसर्च <strong>श्री राम कॉलेज ऑफ़ नर्सिंग</strong> और <strong>श्री राम स्कूल ऑफ़ नर्सिंग</strong> का संचालन करता है, जहाँ नर्सिंग और एलाइड हेल्थ में डिग्री व डिप्लोमा पाठ्यक्रम उपलब्ध हैं।",
    "<strong>Own 100-bed hospital</strong>Clinical exposure from the early semesters.": "<strong>अपना 100 बिस्तरों वाला अस्पताल</strong>शुरुआती सेमेस्टर से ही क्लिनिकल अनुभव।",
    "<strong>Modern laboratories</strong>Anatomy, physiology, microbiology &amp; nursing skills.": "<strong>आधुनिक प्रयोगशालाएँ</strong>एनाटॉमी, फ़िज़ियोलॉजी, माइक्रोबायोलॉजी और नर्सिंग कौशल।",
    "<strong>Well-stocked library</strong>3,500+ books, journals and e-resources.": "<strong>समृद्ध पुस्तकालय</strong>3,500+ पुस्तकें, जर्नल और ई-संसाधन।",
    "<strong>Safe hostels</strong>Separate hostels for girls and boys, with mess.": "<strong>सुरक्षित छात्रावास</strong>छात्राओं और छात्रों के लिए अलग छात्रावास, मेस सहित।",
    "<strong>College transport</strong>Buses on routes around the campus.": "<strong>कॉलेज परिवहन</strong>परिसर के आसपास के मार्गों पर बसें।",
    "<strong>Wi-Fi campus</strong>Plus a gym, sports complex and canteen.": "<strong>वाई-फ़ाई परिसर</strong>साथ में जिम, खेल परिसर और कैंटीन।",
    "More about us": "हमारे बारे में और जानें",
    "Courses we offer": "हमारे पाठ्यक्रम",
    "Degree and diploma programmes in nursing and allied health sciences, with clinical training in our own hospital.":
        "नर्सिंग और एलाइड हेल्थ साइंसेज़ में डिग्री व डिप्लोमा पाठ्यक्रम, हमारे अपने अस्पताल में क्लिनिकल प्रशिक्षण के साथ।",
    '<a href="/courses/">Compare all courses side by side</a>': '<a href="/courses/">सभी पाठ्यक्रमों की तुलना करें</a>',
    "Recognised by Govt. of Haryana": "हरियाणा सरकार से मान्यता प्राप्त",
    "Own 100-Bed Hospital": "अपना 100 बिस्तरों वाला अस्पताल",
    "Recognition and highlights": "मान्यता और मुख्य विशेषताएँ",
    "Life at Shri Ram": "श्री राम में जीवन",
    "A campus built for learning and care": "सीखने और सेवा के लिए बना परिसर",
    "Our pillars": "हमारे आधार स्तंभ",
    "Care. Compassion. Competence.": "सेवा। संवेदना। सक्षमता।",
    "Three values that guide how we teach and how our students serve.": "तीन मूल्य, जो हमारे पढ़ाने और हमारे विद्यार्थियों के सेवा करने के तरीके का मार्गदर्शन करते हैं।",
    "Care": "सेवा",
    "Patient-centred nursing is at the heart of everything we teach, from the first classroom lesson to the hospital ward.":
        "कक्षा के पहले पाठ से लेकर अस्पताल के वार्ड तक, हमारी हर शिक्षा के केंद्र में रोगी-केंद्रित नर्सिंग है।",
    "Compassion": "संवेदना",
    "We shape professionals who treat every patient with dignity, empathy and respect, whatever their background.":
        "हम ऐसे पेशेवर तैयार करते हैं जो हर रोगी के साथ, उसकी पृष्ठभूमि चाहे जो हो, गरिमा, सहानुभूति और सम्मान से पेश आएँ।",
    "Competence": "सक्षमता",
    "Strong science, supervised clinical practice and professional ethics prepare graduates for real-world healthcare.":
        "विज्ञान की मज़बूत समझ, निगरानी में क्लिनिकल अभ्यास और पेशेवर नैतिकता हमारे विद्यार्थियों को वास्तविक स्वास्थ्य सेवा के लिए तैयार करते हैं।",
    "Clinical training": "क्लिनिकल प्रशिक्षण",
    "bed hospital on our own campus": "बिस्तरों का अस्पताल, हमारे अपने परिसर में",
    "Students learn at the bedside under supervision, rotating through wards and services, alongside community health postings in the surrounding villages.":
        "विद्यार्थी निगरानी में रोगी के पास रहकर सीखते हैं, अलग-अलग वार्डों और सेवाओं में बारी-बारी से काम करते हैं, और आसपास के गाँवों में सामुदायिक स्वास्थ्य पोस्टिंग भी करते हैं।",
    "About the hospital": "अस्पताल के बारे में",
    "Campus life": "परिसर जीवन",
    "Everything you need on one campus": "ज़रूरत की हर सुविधा, एक ही परिसर में",
    "Classrooms": "कक्षाएँ",
    "Spacious halls with audio-visual aids.": "ऑडियो-विज़ुअल साधनों से युक्त बड़े हॉल।",
    "Auditorium": "सभागार",
    "Seminars, workshops and events.": "सेमिनार, कार्यशालाएँ और कार्यक्रम।",
    "Skill labs": "स्किल लैब",
    "Hands-on practice before the ward.": "वार्ड में जाने से पहले व्यावहारिक अभ्यास।",
    "Canteen &amp; gym": "कैंटीन और जिम",
    "Hygienic food, fitness and sports.": "स्वच्छ भोजन, फ़िटनेस और खेलकूद।",
    '<a href="/campus-facilities/">Explore all facilities</a>': '<a href="/campus-facilities/">सभी सुविधाएँ देखें</a>',
    "Your path to a nursing career": "नर्सिंग करियर की ओर आपका रास्ता",
    "Admissions follow the rules of DMER Haryana and Pt. B.D. Sharma UHS, Rohtak.":
        "प्रवेश DMER हरियाणा और पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक के नियमों के अनुसार होते हैं।",
    "Check eligibility": "पात्रता जाँचें",
    "10+2 with the required subjects and marks; minimum age 17 by 31 December.": "आवश्यक विषयों और अंकों के साथ 10+2; 31 दिसंबर तक न्यूनतम आयु 17 वर्ष।",
    "Apply / appear": "आवेदन / परीक्षा",
    "B.Sc courses: UHSR entrance test &amp; counselling. ANM/GNM: merit-based.": "बी.एससी. पाठ्यक्रम: UHSR प्रवेश परीक्षा और काउंसलिंग। एएनएम/जीएनएम: मेरिट के आधार पर।",
    "Choose Shri Ram": "श्री राम चुनें",
    "Select Shri Ram College of Nursing, Digrota, in counselling, or contact us.": "काउंसलिंग में श्री राम कॉलेज ऑफ़ नर्सिंग, डिगरोता चुनें, या हमसे संपर्क करें।",
    "Report &amp; enrol": "रिपोर्ट करें और दाखिला लें",
    "Bring original documents, pay the fee and begin your journey.": "मूल दस्तावेज़ लाएँ, शुल्क जमा करें और अपनी यात्रा शुरू करें।",
    "Admission details": "प्रवेश की जानकारी",
    "Latest": "ताज़ा",
    "Notices &amp; announcements": "सूचनाएँ और घोषणाएँ",
    '<a href="/notices/">All notices</a>': '<a href="/notices/">सभी सूचनाएँ</a>',
    "Begin your career in healthcare": "स्वास्थ्य सेवा में अपना करियर शुरू करें",
    "Talk to our admissions team about courses, eligibility, fees and hostel availability.":
        "पाठ्यक्रम, पात्रता, शुल्क और छात्रावास के बारे में हमारी प्रवेश टीम से बात करें।",
    "Contact Admissions": "प्रवेश कार्यालय से संपर्क करें",

    # ------------------------------------------------------------ ABOUT
    "Shri Ram College of Medical Science &amp; Research, Digrota (Mahendragarh), is a private, co-educational institution for nursing and allied health education. Through <strong>Shri Ram College of Nursing</strong> (degree programmes) and <strong>Shri Ram School of Nursing</strong> (diploma programmes), it has served students of Mahendragarh and the surrounding districts since 2012.":
        "श्री राम कॉलेज ऑफ़ मेडिकल साइंस एंड रिसर्च, डिगरोता (महेंद्रगढ़) नर्सिंग और एलाइड हेल्थ शिक्षा का एक निजी, सह-शिक्षा संस्थान है। <strong>श्री राम कॉलेज ऑफ़ नर्सिंग</strong> (डिग्री पाठ्यक्रम) और <strong>श्री राम स्कूल ऑफ़ नर्सिंग</strong> (डिप्लोमा पाठ्यक्रम) के माध्यम से यह 2012 से महेंद्रगढ़ और आसपास के ज़िलों के विद्यार्थियों की सेवा कर रहा है।",
    "The college is approved by the Indian Nursing Council (INC), New Delhi, and the Haryana Nurses &amp; Midwives Council, and is affiliated to Pt. B.D. Sharma University of Health Sciences, Rohtak. The campus has spacious, fully furnished classrooms, well-established laboratories, a comprehensive library and an auditorium. Students also train at our own 100-bed hospital, which gives them the clinical exposure a good nurse needs.":
        "कॉलेज भारतीय नर्सिंग परिषद (INC), नई दिल्ली और हरियाणा नर्सेज़ एवं मिडवाइव्स काउंसिल से अनुमोदित है तथा पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक से संबद्ध है। परिसर में बड़ी, पूरी तरह सुसज्जित कक्षाएँ, सुव्यवस्थित प्रयोगशालाएँ, एक समृद्ध पुस्तकालय और सभागार है। विद्यार्थी हमारे अपने 100 बिस्तरों वाले अस्पताल में भी प्रशिक्षण लेते हैं, जहाँ उन्हें वह क्लिनिकल अनुभव मिलता है जो एक अच्छी नर्स के लिए ज़रूरी है।",
    "The institution is run by <strong>Shri Ram Krishan Param Hans Shiksha Parishad</strong> and is part of the <strong>Shri Ram Group of Institutions (SRGI), Haryana</strong>. On the same campus, the group also runs <strong>Shri Ram Ayurvedic Medical College &amp; Hospital</strong>, offering the BAMS programme, approved by CCIM, New Delhi (Ministry of AYUSH) and affiliated to Shri Krishna AYUSH University, Kurukshetra.":
        "संस्थान का संचालन <strong>श्री राम कृष्ण परम हंस शिक्षा परिषद</strong> द्वारा किया जाता है और यह <strong>श्री राम ग्रुप ऑफ़ इंस्टीट्यूशंस (SRGI), हरियाणा</strong> का हिस्सा है। इसी परिसर में ग्रुप <strong>श्री राम आयुर्वेदिक मेडिकल कॉलेज एवं अस्पताल</strong> भी चलाता है, जहाँ बीएएमएस पाठ्यक्रम उपलब्ध है — यह CCIM, नई दिल्ली (आयुष मंत्रालय) से अनुमोदित और श्री कृष्ण आयुष विश्वविद्यालय, कुरुक्षेत्र से संबद्ध है।",
    "Please confirm the year each institution was established (online sources say 2012 for the group and 2019 for the College of Nursing) and the name of the managing trust or society.":
        "कृपया प्रत्येक संस्थान की स्थापना का वर्ष (ऑनलाइन स्रोतों के अनुसार ग्रुप के लिए 2012 और कॉलेज ऑफ़ नर्सिंग के लिए 2019) और संचालक ट्रस्ट या सोसाइटी का नाम पुष्टि करें।",
    "Our Vision": "हमारा दृष्टिकोण",
    "To be a leading centre of nursing and paramedical education in rural Haryana, producing competent, ethical and compassionate healthcare professionals who serve their communities.":
        "ग्रामीण हरियाणा में नर्सिंग और पैरामेडिकल शिक्षा का अग्रणी केंद्र बनना, जो ऐसे सक्षम, नैतिक और संवेदनशील स्वास्थ्य पेशेवर तैयार करे जो अपने समाज की सेवा करें।",
    "Our Mission": "हमारा लक्ष्य",
    "Deliver INC and university-standard education with strong clinical training": "मज़बूत क्लिनिकल प्रशिक्षण के साथ INC और विश्वविद्यालय मानकों के अनुरूप शिक्षा देना",
    "Make quality healthcare education accessible to rural students, especially young women": "गुणवत्तापूर्ण स्वास्थ्य शिक्षा को ग्रामीण विद्यार्थियों, विशेषकर युवतियों, तक पहुँचाना",
    "Instil empathy, discipline and professional ethics": "सहानुभूति, अनुशासन और पेशेवर नैतिकता का विकास करना",
    "Serve the community through health camps and outreach": "स्वास्थ्य शिविरों और जनसंपर्क कार्यक्रमों से समाज की सेवा करना",
    "The Vision and Mission above are drafts written for the website. Please review or replace them with the college's official statements.":
        "ऊपर दिए गए दृष्टिकोण और लक्ष्य वेबसाइट के लिए लिखे गए प्रारूप हैं। कृपया इनकी समीक्षा करें या इन्हें कॉलेज के आधिकारिक कथनों से बदलें।",
    "Key facts": "मुख्य तथ्य",
    "At a glance": "एक नज़र में",
    "Location": "स्थान",
    "Managing society": "संचालक संस्था",
    "Shri Ram Krishan Param Hans Shiksha Parishad (Shri Ram Group of Institutions, Haryana)": "श्री राम कृष्ण परम हंस शिक्षा परिषद (श्री राम ग्रुप ऑफ़ इंस्टीट्यूशंस, हरियाणा)",
    "Type": "प्रकार",
    "Private (self-financed), co-educational": "निजी (स्व-वित्तपोषित), सह-शिक्षा",
    "Approvals": "अनुमोदन",
    "Indian Nursing Council (INC), New Delhi; Haryana Nurses &amp; Midwives Council (HNRC)": "भारतीय नर्सिंग परिषद (INC), नई दिल्ली; हरियाणा नर्सेज़ एवं मिडवाइव्स काउंसिल (HNRC)",
    "B.Sc Nursing, Post Basic B.Sc Nursing, B.Sc Paramedical Science, GNM, ANM": "बी.एससी. नर्सिंग, पोस्ट बेसिक बी.एससी. नर्सिंग, बी.एससी. पैरामेडिकल साइंस, जीएनएम, एएनएम",
    "Own 100-bed hospital for clinical training": "क्लिनिकल प्रशिक्षण के लिए अपना 100 बिस्तरों वाला अस्पताल",
    "Residential": "आवास",
    "Leadership": "नेतृत्व",
    "Chairman": "अध्यक्ष",
    "Sh. Sukesh Diwan": "श्री सुकेश दीवान",
    "Chairman, Shri Ram Group of Institutions": "अध्यक्ष, श्री राम ग्रुप ऑफ़ इंस्टीट्यूशंस",
    "CEO": "सीईओ",
    "Sh. Manish Diwan": "श्री मनीष दीवान",
    "Chief Executive Officer, Shri Ram Group of Institutions": "मुख्य कार्यकारी अधिकारी, श्री राम ग्रुप ऑफ़ इंस्टीट्यूशंस",
    "Director": "निदेशक",
    "Sh. Hawa Singh": "श्री हवा सिंह",
    "Name to be added": "नाम जोड़ा जाना है",
    "Principal's name, photo and message.": "प्रधानाचार्य का नाम, फ़ोटो और संदेश।",
    "Leadership names are taken from the college's 2018–19 admission notice posted on its Google listing. Please confirm they are current and send photos and messages.":
        "नेतृत्व के नाम कॉलेज की गूगल लिस्टिंग पर लगी 2018–19 की प्रवेश सूचना से लिए गए हैं। कृपया पुष्टि करें कि ये वर्तमान हैं, और फ़ोटो व संदेश भेजें।",

    # ------------------------------------------------------------ COURSES
    "We offer degree and diploma programmes in nursing and allied health sciences. All nursing programmes are approved by the Indian Nursing Council and the Haryana Nurses &amp; Midwives Council. Degrees are awarded by Pt. B.D. Sharma University of Health Sciences, Rohtak.":
        "हम नर्सिंग और एलाइड हेल्थ साइंसेज़ में डिग्री व डिप्लोमा पाठ्यक्रम चलाते हैं। सभी नर्सिंग पाठ्यक्रम भारतीय नर्सिंग परिषद और हरियाणा नर्सेज़ एवं मिडवाइव्स काउंसिल से अनुमोदित हैं। डिग्री पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक द्वारा प्रदान की जाती है।",
    "Programme": "पाठ्यक्रम",
    "Minimum qualification": "न्यूनतम योग्यता",
    '<a href="/courses/bsc-nursing/">B.Sc Nursing</a>': '<a href="/courses/bsc-nursing/">बी.एससी. नर्सिंग</a>',
    '<a href="/courses/post-basic-bsc-nursing/">Post Basic B.Sc Nursing</a>': '<a href="/courses/post-basic-bsc-nursing/">पोस्ट बेसिक बी.एससी. नर्सिंग</a>',
    '<a href="/courses/bsc-paramedical-science/">B.Sc Paramedical Science</a>': '<a href="/courses/bsc-paramedical-science/">बी.एससी. पैरामेडिकल साइंस</a>',
    '<a href="/courses/gnm/">GNM</a>': '<a href="/courses/gnm/">जीएनएम</a>',
    '<a href="/courses/anm/">ANM</a>': '<a href="/courses/anm/">एएनएम</a>',
    "UG Degree": "स्नातक डिग्री",
    "10+2 with PCB &amp; English (50%)": "PCB व अंग्रेज़ी के साथ 10+2 (50%)",
    "10+2 + GNM, registered nurse &amp; midwife": "10+2 + जीएनएम, पंजीकृत नर्स व मिडवाइफ",
    "10+2 with Science": "विज्ञान के साथ 10+2",
    "As approved": "स्वीकृति अनुसार",
    "10+2 (any stream)": "10+2 (कोई भी संकाय)",
    "BAMS (Ayurveda) *": "बीएएमएस (आयुर्वेद) *",
    "5½ years": "5½ वर्ष",
    "10+2 with PCB + NEET": "PCB के साथ 10+2 + NEET",
    "* BAMS is offered by Shri Ram Ayurvedic Medical College &amp; Hospital on the same campus (CCIM / Ministry of AYUSH; Shri Krishna AYUSH University, Kurukshetra). Seat numbers are the approved intake published by the regulators and may change each session.":
        "* बीएएमएस इसी परिसर में श्री राम आयुर्वेदिक मेडिकल कॉलेज एवं अस्पताल द्वारा चलाया जाता है (CCIM / आयुष मंत्रालय; श्री कृष्ण आयुष विश्वविद्यालय, कुरुक्षेत्र)। सीटों की संख्या नियामकों द्वारा प्रकाशित स्वीकृत प्रवेश क्षमता है और हर सत्र में बदल सकती है।",
    "Explore each course": "हर पाठ्यक्रम के बारे में जानें",
    "Not sure which course fits you?": "तय नहीं कर पा रहे कि कौन-सा पाठ्यक्रम आपके लिए सही है?",
    "Our admissions team can guide you on eligibility, seats and career paths.": "हमारी प्रवेश टीम पात्रता, सीटों और करियर विकल्पों पर आपका मार्गदर्शन कर सकती है।",
    "Talk to admissions": "प्रवेश टीम से बात करें",

    # ------------------------------------------------------------ COURSE PAGES
    "4 years (including internship)": "4 वर्ष (इंटर्नशिप सहित)",
    "UHSR entrance test &amp; counselling": "UHSR प्रवेश परीक्षा और काउंसलिंग",
    "10+2 from a recognised board with Physics, Chemistry, Biology and English": "मान्यता प्राप्त बोर्ड से भौतिकी, रसायन विज्ञान, जीव विज्ञान और अंग्रेज़ी के साथ 10+2",
    "Minimum 50% aggregate in PCB (relaxation for SC/ST/OBC as per government norms)": "PCB में न्यूनतम 50% कुल अंक (SC/ST/OBC को सरकारी नियमों के अनुसार छूट)",
    "Minimum age 17 years on or before 31 December of the admission year": "प्रवेश वर्ष की 31 दिसंबर तक न्यूनतम आयु 17 वर्ष",
    "Admission through the entrance test and counselling conducted by Pt. B.D. Sharma UHS, Rohtak":
        "पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक द्वारा आयोजित प्रवेश परीक्षा और काउंसलिंग के माध्यम से प्रवेश",
    "What you will study": "आप क्या पढ़ेंगे",
    "Anatomy, physiology, biochemistry, microbiology and pharmacology": "एनाटॉमी, फ़िज़ियोलॉजी, बायोकेमिस्ट्री, माइक्रोबायोलॉजी और फ़ार्माकोलॉजी",
    "Nursing foundations and adult health (medical-surgical) nursing": "नर्सिंग फ़ाउंडेशन और एडल्ट हेल्थ (मेडिकल-सर्जिकल) नर्सिंग",
    "Child health, mental health and community health nursing": "शिशु स्वास्थ्य, मानसिक स्वास्थ्य और सामुदायिक स्वास्थ्य नर्सिंग",
    "Midwifery and obstetrical nursing": "मिडवाइफरी और प्रसूति नर्सिंग",
    "Nursing research, management and professional ethics": "नर्सिंग अनुसंधान, प्रबंधन और पेशेवर नैतिकता",
    "Supervised clinical practice in our 100-bed hospital and the community": "हमारे 100 बिस्तरों वाले अस्पताल और समुदाय में निगरानी में क्लिनिकल अभ्यास",
    "Career opportunities": "करियर के अवसर",
    "Staff nurse in government and private hospitals": "सरकारी और निजी अस्पतालों में स्टाफ़ नर्स",
    "Community health nurse / public health programmes": "सामुदायिक स्वास्थ्य नर्स / जन स्वास्थ्य कार्यक्रम",
    "Military Nursing Service, railways and ESIC hospitals": "मिलिट्री नर्सिंग सर्विस, रेलवे और ESIC अस्पताल",
    "Nursing tutor (with higher qualifications)": "नर्सिंग ट्यूटर (उच्च योग्यता के साथ)",
    "Opportunities abroad, including the Middle East and the UK, after licensing exams": "लाइसेंसिंग परीक्षाओं के बाद विदेश में अवसर, जैसे मध्य-पूर्व और ब्रिटेन",
    "Higher studies: M.Sc Nursing, MBA in Hospital Management, MPH": "उच्च शिक्षा: एम.एससी. नर्सिंग, हॉस्पिटल मैनेजमेंट में एमबीए, एमपीएच",
    "Ready to apply?": "आवेदन के लिए तैयार हैं?",
    "See the admission process, documents required and fees, or send us an enquiry.": "प्रवेश प्रक्रिया, आवश्यक दस्तावेज़ और शुल्क देखें, या हमें पूछताछ भेजें।",
    "Passed 10+2 (Science stream preferred)": "10+2 उत्तीर्ण (विज्ञान संकाय को प्राथमिकता)",
    "Passed the GNM (General Nursing &amp; Midwifery) course": "जीएनएम (जनरल नर्सिंग एवं मिडवाइफरी) पाठ्यक्रम उत्तीर्ण",
    "Registered nurse and midwife with a State Nursing Registration Council": "किसी राज्य नर्सिंग पंजीकरण परिषद में पंजीकृत नर्स और मिडवाइफ",
    "Advanced nursing practice and nursing education": "उन्नत नर्सिंग अभ्यास और नर्सिंग शिक्षा",
    "Maternal, child and mental health nursing": "मातृ, शिशु और मानसिक स्वास्थ्य नर्सिंग",
    "Introduction to nursing research and statistics": "नर्सिंग अनुसंधान और सांख्यिकी का परिचय",
    "Nursing administration and ward management": "नर्सिंग प्रशासन और वार्ड प्रबंधन",
    "Senior staff nurse and ward in-charge roles": "सीनियर स्टाफ़ नर्स और वार्ड इंचार्ज की भूमिकाएँ",
    "Public health and community nursing": "जन स्वास्थ्य और सामुदायिक नर्सिंग",
    "Nursing tutor / clinical instructor": "नर्सिंग ट्यूटर / क्लिनिकल इंस्ट्रक्टर",
    "Please list the specialisations offered under B.Sc Paramedical Science (e.g. Medical Lab Technology, Operation Theatre Technology, Radiology &amp; Imaging) with seats for each.":
        "कृपया बी.एससी. पैरामेडिकल साइंस के अंतर्गत उपलब्ध विशेषज्ञताओं (जैसे मेडिकल लैब टेक्नोलॉजी, ऑपरेशन थिएटर टेक्नोलॉजी, रेडियोलॉजी एवं इमेजिंग) की सूची, हर एक की सीटों के साथ, भेजें।",
    "Degree awarded by": "डिग्री प्रदाता",
    "Mode": "माध्यम",
    "UHSR counselling / merit": "UHSR काउंसलिंग / मेरिट",
    "10+2 with Science from a recognised board (CBSE, ISC, HBSE or equivalent)": "मान्यता प्राप्त बोर्ड (CBSE, ISC, HBSE या समकक्ष) से विज्ञान के साथ 10+2",
    "Other conditions as notified by Pt. B.D. Sharma UHS, Rohtak for the session": "सत्र के लिए पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक द्वारा अधिसूचित अन्य शर्तें",
    "Human anatomy, physiology and biochemistry": "मानव शरीर रचना, फ़िज़ियोलॉजी और बायोकेमिस्ट्री",
    "Pathology and microbiology": "पैथोलॉजी और माइक्रोबायोलॉजी",
    "Specialisation subjects and hands-on laboratory work": "विशेषज्ञता के विषय और प्रयोगशाला में व्यावहारिक कार्य",
    "Hospital postings in diagnostic and operating departments": "जाँच और ऑपरेशन विभागों में अस्पताल पोस्टिंग",
    "Medical laboratory, radiology or operation theatre technologist": "मेडिकल लैब, रेडियोलॉजी या ऑपरेशन थिएटर टेक्नोलॉजिस्ट",
    "Diagnostic centres and blood banks": "जाँच केंद्र और ब्लड बैंक",
    "Hospital and emergency services": "अस्पताल और आपातकालीन सेवाएँ",
    "Higher studies: M.Sc in the chosen allied-health field": "उच्च शिक्षा: चुने गए एलाइड हेल्थ क्षेत्र में एम.एससी.",
    "Please confirm the approved GNM intake (seats) for the current session.": "कृपया वर्तमान सत्र के लिए जीएनएम की स्वीकृत सीटों की पुष्टि करें।",
    "As approved by INC / HNRC": "INC / HNRC की स्वीकृति अनुसार",
    "Examining body": "परीक्षा निकाय",
    "10+2 from a recognised board (Science preferred; other streams as per INC norms)": "मान्यता प्राप्त बोर्ड से 10+2 (विज्ञान को प्राथमिकता; अन्य संकाय INC नियमों के अनुसार)",
    "Bio-sciences and behavioural sciences": "जैव विज्ञान और व्यवहार विज्ञान",
    "Fundamentals of nursing and first aid": "नर्सिंग के मूल सिद्धांत और प्राथमिक उपचार",
    "Medical-surgical, community health and mental health nursing": "मेडिकल-सर्जिकल, सामुदायिक स्वास्थ्य और मानसिक स्वास्थ्य नर्सिंग",
    "Child health nursing and midwifery": "शिशु स्वास्थ्य नर्सिंग और मिडवाइफरी",
    "Clinical practice in our hospital and community postings": "हमारे अस्पताल में क्लिनिकल अभ्यास और सामुदायिक पोस्टिंग",
    "Further study: Post Basic B.Sc Nursing": "आगे की पढ़ाई: पोस्ट बेसिक बी.एससी. नर्सिंग",
    "Regulated by": "नियामक",
    "Selection": "चयन",
    "Merit based": "मेरिट के आधार पर",
    "10+2 in Arts, Science, Commerce or Health Care Science (Vocational) from a recognised board": "मान्यता प्राप्त बोर्ड से कला, विज्ञान, वाणिज्य या हेल्थ केयर साइंस (व्यावसायिक) में 10+2",
    "Students who passed 10+2 through the National Institute of Open Schooling (NIOS) may also apply": "राष्ट्रीय मुक्त विद्यालयी शिक्षा संस्थान (NIOS) से 10+2 उत्तीर्ण विद्यार्थी भी आवेदन कर सकते हैं",
    "Community health nursing and health promotion": "सामुदायिक स्वास्थ्य नर्सिंग और स्वास्थ्य संवर्धन",
    "Primary health care and first aid": "प्राथमिक स्वास्थ्य देखभाल और प्राथमिक उपचार",
    "Midwifery and maternal care": "मिडवाइफरी और मातृ देखभाल",
    "Health centre management": "स्वास्थ्य केंद्र प्रबंधन",
    "ANM / health worker at sub-centres and PHCs": "उप-केंद्रों और प्राथमिक स्वास्थ्य केंद्रों (PHC) पर एएनएम / स्वास्थ्य कार्यकर्ता",
    "National health programmes and immunisation drives": "राष्ट्रीय स्वास्थ्य कार्यक्रम और टीकाकरण अभियान",
    "Hospitals, nursing homes and maternity centres": "अस्पताल, नर्सिंग होम और प्रसूति केंद्र",
    "Further study: GNM and nursing degrees": "आगे की पढ़ाई: जीएनएम और नर्सिंग डिग्रियाँ",

    # ------------------------------------------------------------ ADMISSIONS
    "Admissions to Shri Ram College of Nursing and Shri Ram School of Nursing follow the rules of the Indian Nursing Council, the Department of Medical Education &amp; Research (DMER), Haryana, and Pt. B.D. Sharma University of Health Sciences, Rohtak.":
        "श्री राम कॉलेज ऑफ़ नर्सिंग और श्री राम स्कूल ऑफ़ नर्सिंग में प्रवेश भारतीय नर्सिंग परिषद, चिकित्सा शिक्षा एवं अनुसंधान विभाग (DMER), हरियाणा और पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक के नियमों के अनुसार होते हैं।",
    "B.Sc Nursing, Post Basic B.Sc &amp; B.Sc Paramedical": "बी.एससी. नर्सिंग, पोस्ट बेसिक बी.एससी. और बी.एससी. पैरामेडिकल",
    "Register for the entrance test / counselling on the UHSR admissions portal (uhsrcetadmissions.in) when it is notified.":
        "अधिसूचना जारी होने पर UHSR प्रवेश पोर्टल (uhsrcetadmissions.in) पर प्रवेश परीक्षा / काउंसलिंग के लिए पंजीकरण करें।",
    "Appear in the entrance test (CET) conducted by Pt. B.D. Sharma UHS, Rohtak.": "पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय, रोहतक द्वारा आयोजित प्रवेश परीक्षा (CET) में शामिल हों।",
    "Fill in choices during online counselling and select <em>Shri Ram College of Nursing, Digrota, Mahendergarh</em>.":
        "ऑनलाइन काउंसलिंग में विकल्प भरते समय <em>श्री राम कॉलेज ऑफ़ नर्सिंग, डिगरोता, महेंद्रगढ़</em> चुनें।",
    "On allotment, report to the college with original documents and pay the fee within the given dates.": "सीट आवंटित होने पर मूल दस्तावेज़ों के साथ कॉलेज में रिपोर्ट करें और निर्धारित तिथियों के भीतर शुल्क जमा करें।",
    "Management-quota seats are filled as per state rules. Contact the college office for details.": "मैनेजमेंट कोटे की सीटें राज्य के नियमों के अनुसार भरी जाती हैं। विवरण के लिए कॉलेज कार्यालय से संपर्क करें।",
    "GNM &amp; ANM": "जीएनएम और एएनएम",
    "Obtain the application form from the college office (or enquire online).": "कॉलेज कार्यालय से आवेदन पत्र प्राप्त करें (या ऑनलाइन पूछताछ करें)।",
    "Admission is made on merit in the qualifying examination, as per HNRC / Govt. of Haryana norms.": "HNRC / हरियाणा सरकार के नियमों के अनुसार योग्यता परीक्षा की मेरिट पर प्रवेश दिया जाता है।",
    "Attend document verification.": "दस्तावेज़ सत्यापन के लिए उपस्थित हों।",
    "Pay the fee and complete enrolment.": "शुल्क जमा करें और दाखिला पूरा करें।",
    "Eligibility at a glance": "पात्रता एक नज़र में",
    "Course": "पाठ्यक्रम",
    "Age": "आयु",
    "10+2 with PCB + English, 50% in PCB (relaxation for reserved categories)": "PCB + अंग्रेज़ी के साथ 10+2, PCB में 50% (आरक्षित वर्गों को छूट)",
    "17 years by 31 Dec": "31 दिसंबर तक 17 वर्ष",
    "10+2 + GNM; registered nurse &amp; midwife": "10+2 + जीएनएम; पंजीकृत नर्स व मिडवाइफ",
    "As per UHSR": "UHSR के अनुसार",
    "10+2 (as per INC norms)": "10+2 (INC नियमों के अनुसार)",
    "10+2 in any stream (incl. NIOS / vocational health care)": "किसी भी संकाय में 10+2 (NIOS / व्यावसायिक हेल्थ केयर सहित)",
    "Documents required": "आवश्यक दस्तावेज़",
    "10th and 12th mark sheets and certificates (originals + 2 self-attested copies)": "10वीं और 12वीं की अंकतालिकाएँ व प्रमाण पत्र (मूल + 2 स्व-सत्यापित प्रतियाँ)",
    "Entrance test score card and allotment letter (B.Sc courses)": "प्रवेश परीक्षा का स्कोर कार्ड और आवंटन पत्र (बी.एससी. पाठ्यक्रम)",
    "Haryana domicile / resident certificate (for state-quota seats)": "हरियाणा का अधिवास / निवास प्रमाण पत्र (राज्य कोटे की सीटों के लिए)",
    "Caste / category certificate, if applicable": "जाति / वर्ग प्रमाण पत्र, यदि लागू हो",
    "Aadhaar card and 6 recent passport-size photographs": "आधार कार्ड और 6 हाल ही के पासपोर्ट साइज़ फ़ोटो",
    "Character certificate from the last institution attended": "पिछले संस्थान से चरित्र प्रमाण पत्र",
    "Migration certificate (for boards outside Haryana)": "माइग्रेशन प्रमाण पत्र (हरियाणा से बाहर के बोर्डों के लिए)",
    "Medical fitness certificate": "मेडिकल फ़िटनेस प्रमाण पत्र",
    "GNM certificate and nursing council registration (Post Basic B.Sc only)": "जीएनएम प्रमाण पत्र और नर्सिंग परिषद पंजीकरण (केवल पोस्ट बेसिक बी.एससी.)",
    "Please confirm this document list and add the admission office timings.": "कृपया इस दस्तावेज़ सूची की पुष्टि करें और प्रवेश कार्यालय का समय जोड़ें।",
    "Frequently asked questions": "अक्सर पूछे जाने वाले प्रश्न",
    "Is the college approved by the Indian Nursing Council?": "क्या कॉलेज भारतीय नर्सिंग परिषद से अनुमोदित है?",
    'Yes. Our nursing programmes are approved by the Indian Nursing Council (INC), New Delhi, and the Haryana Nurses &amp; Midwives Council. See <a href="/approvals/">Approvals &amp; Affiliations</a>.':
        'हाँ। हमारे नर्सिंग पाठ्यक्रम भारतीय नर्सिंग परिषद (INC), नई दिल्ली और हरियाणा नर्सेज़ एवं मिडवाइव्स काउंसिल से अनुमोदित हैं। देखें <a href="/approvals/">मान्यता एवं संबद्धता</a>।',
    "Which university awards the degree?": "डिग्री कौन-सा विश्वविद्यालय देता है?",
    "Degrees are awarded by Pt. B.D. Sharma University of Health Sciences (UHSR), Rohtak.": "डिग्री पं. बी.डी. शर्मा स्वास्थ्य विज्ञान विश्वविद्यालय (UHSR), रोहतक द्वारा दी जाती है।",
    "Is hostel accommodation available?": "क्या छात्रावास की सुविधा उपलब्ध है?",
    "Yes. There are separate hostels for girls and boys, with mess facilities and security.": "हाँ। छात्राओं और छात्रों के लिए मेस और सुरक्षा सहित अलग-अलग छात्रावास हैं।",
    "Is the college co-educational?": "क्या कॉलेज में सह-शिक्षा है?",
    "Yes. Both male and female candidates can apply, subject to the eligibility rules of each course.": "हाँ। हर पाठ्यक्रम के पात्रता नियमों के अधीन, छात्र और छात्राएँ दोनों आवेदन कर सकते हैं।",
    "Where do students do their clinical training?": "विद्यार्थी क्लिनिकल प्रशिक्षण कहाँ करते हैं?",
    'At our own 100-bed hospital, plus community health postings. See <a href="/hospital/">Hospital</a>.':
        'हमारे अपने 100 बिस्तरों वाले अस्पताल में, और साथ में सामुदायिक स्वास्थ्य पोस्टिंग। देखें <a href="/hospital/">अस्पताल</a>।',
    "What are the fees?": "शुल्क कितना है?",
    'Fees follow the structure notified by the Government of Haryana. See <a href="/fee-structure/">Fee Structure</a>.':
        'शुल्क हरियाणा सरकार द्वारा अधिसूचित संरचना के अनुसार है। देखें <a href="/fee-structure/">शुल्क संरचना</a>।',
    "Admission enquiry": "प्रवेश पूछताछ",
    "Leave your details and our admissions office will call you back with guidance on eligibility, counselling dates, fees and hostels.":
        "अपना विवरण छोड़ें, हमारा प्रवेश कार्यालय आपको वापस कॉल करके पात्रता, काउंसलिंग की तिथियों, शुल्क और छात्रावास के बारे में मार्गदर्शन देगा।",
    "Course and eligibility guidance": "पाठ्यक्रम और पात्रता पर मार्गदर्शन",
    "Help with UHSR counselling": "UHSR काउंसलिंग में सहायता",
    "Hostel and transport information": "छात्रावास और परिवहन की जानकारी",

    # ------------------------------------------------------------ FEES
    "Fees at Shri Ram College of Nursing follow the fee structure for private colleges notified by the Government of Haryana (Haryana Govt. Gazette, 21 June 2024, Annexure-VI).":
        "श्री राम कॉलेज ऑफ़ नर्सिंग का शुल्क हरियाणा सरकार द्वारा निजी कॉलेजों के लिए अधिसूचित शुल्क संरचना के अनुसार है (हरियाणा सरकार राजपत्र, 21 जून 2024, अनुलग्नक-VI)।",
    "Please add the college's own fee sheet for the current session (tuition, hostel, mess, transport) for every course, including GNM, ANM and B.Sc Paramedical.":
        "कृपया वर्तमान सत्र के लिए हर पाठ्यक्रम (जीएनएम, एएनएम और बी.एससी. पैरामेडिकल सहित) की कॉलेज की अपनी शुल्क सूची (ट्यूशन, छात्रावास, मेस, परिवहन) जोड़ें।",
    "Government-notified fee norms for private colleges": "निजी कॉलेजों के लिए सरकार द्वारा अधिसूचित शुल्क मानदंड",
    "Fee head": "शुल्क मद",
    "B.Sc &amp; Post Basic B.Sc Nursing (per year)": "बी.एससी. और पोस्ट बेसिक बी.एससी. नर्सिंग (प्रति वर्ष)",
    "Tuition fee (incl. development charges)": "ट्यूशन शुल्क (विकास शुल्क सहित)",
    "₹60,000, with an annual increase of 5%": "₹60,000, हर वर्ष 5% की वृद्धि के साथ",
    "Library fee": "पुस्तकालय शुल्क",
    "Sports &amp; medical charges": "खेल एवं चिकित्सा शुल्क",
    "Internet charges": "इंटरनेट शुल्क",
    "Examination &amp; university charges": "परीक्षा एवं विश्वविद्यालय शुल्क",
    "As actual": "वास्तविक अनुसार",
    "Hostel fee": "छात्रावास शुल्क",
    "Not more than ₹60,000 or actual, whichever is less (no charge for fan &amp; lighting)": "₹60,000 या वास्तविक, जो भी कम हो (पंखे व बिजली का कोई शुल्क नहीं)",
    "Mess charges": "मेस शुल्क",
    "Transport (if availed)": "परिवहन (यदि लिया जाए)",
    "NRI seats (15%)": "एनआरआई सीटें (15%)",
    "USD 15,000 for the entire course": "पूरे पाठ्यक्रम के लिए 15,000 अमेरिकी डॉलर",
    'Source: Haryana Govt. Gazette (Extra.), 21 June 2024, Annexure-VI, <a href="{{FEE_PDF}}">download PDF</a>.':
        'स्रोत: हरियाणा सरकार राजपत्र (असाधारण), 21 जून 2024, अनुलग्नक-VI, <a href="{{FEE_PDF}}">PDF डाउनलोड करें</a>।',
    "Scholarships for SC/BC and other eligible students are available under Government of Haryana and central schemes, subject to their rules. Ask the college office for guidance on applying.":
        "SC/BC और अन्य पात्र विद्यार्थियों के लिए हरियाणा सरकार और केंद्र सरकार की योजनाओं के तहत, उनके नियमों के अनुसार, छात्रवृत्ति उपलब्ध है। आवेदन में मार्गदर्शन के लिए कॉलेज कार्यालय से संपर्क करें।",
    "Please confirm which scholarship schemes students of the college commonly use (e.g. Post-Matric Scholarship on the Haryana Saral / NSP portal).":
        "कृपया बताएँ कि कॉलेज के विद्यार्थी आमतौर पर कौन-सी छात्रवृत्ति योजनाओं का लाभ लेते हैं (जैसे हरियाणा सरल / NSP पोर्टल पर पोस्ट-मैट्रिक छात्रवृत्ति)।",

    # ------------------------------------------------------------ APPROVALS
    "Our programmes are approved by the national and state regulators for nursing education, and our degrees are awarded by the state health sciences university.":
        "हमारे पाठ्यक्रम नर्सिंग शिक्षा के राष्ट्रीय और राज्य नियामकों से अनुमोदित हैं, और हमारी डिग्रियाँ राज्य का स्वास्थ्य विज्ञान विश्वविद्यालय प्रदान करता है।",
    "National regulator": "राष्ट्रीय नियामक",
    "Approves the B.Sc Nursing, Post Basic B.Sc Nursing, GNM and ANM programmes and their intake.":
        "बी.एससी. नर्सिंग, पोस्ट बेसिक बी.एससी. नर्सिंग, जीएनएम और एएनएम पाठ्यक्रमों तथा उनकी सीटों को अनुमोदित करती है।",
    '<a href="https://www.indiannursingcouncil.org" target="_blank" rel="noopener">indiannursingcouncil.org ↗</a>':
        '<a href="https://www.indiannursingcouncil.org" target="_blank" rel="noopener">indiannursingcouncil.org ↗</a>',
    "State council": "राज्य परिषद",
    "Recognises the institution in Haryana and registers our graduates as nurses and midwives.": "हरियाणा में संस्थान को मान्यता देती है और हमारे उत्तीर्ण विद्यार्थियों का नर्स व मिडवाइफ के रूप में पंजीकरण करती है।",
    "Affiliating university": "संबद्धता देने वाला विश्वविद्यालय",
    "Awards our degrees, conducts entrance tests, counselling and examinations (including GNM finals).": "हमारी डिग्रियाँ प्रदान करता है और प्रवेश परीक्षा, काउंसलिंग व परीक्षाएँ (जीएनएम की अंतिम परीक्षा सहित) आयोजित करता है।",
    '<a href="https://www.uhsr.ac.in" target="_blank" rel="noopener">uhsr.ac.in ↗</a>':
        '<a href="https://www.uhsr.ac.in" target="_blank" rel="noopener">uhsr.ac.in ↗</a>',
    "State government": "राज्य सरकार",
    "DMER, Government of Haryana": "DMER, हरियाणा सरकार",
    "Recognition of the institution; admission counselling and fee norms for nursing colleges.": "संस्थान की मान्यता; नर्सिंग कॉलेजों के लिए प्रवेश काउंसलिंग और शुल्क मानदंड।",
    '<a href="https://dmer.haryana.gov.in" target="_blank" rel="noopener">dmer.haryana.gov.in ↗</a>':
        '<a href="https://dmer.haryana.gov.in" target="_blank" rel="noopener">dmer.haryana.gov.in ↗</a>',
    "Approval documents": "अनुमोदन दस्तावेज़",
    "Document": "दस्तावेज़",
    "Reference / date": "संदर्भ / तिथि",
    "Download": "डाउनलोड",
    "INC approval letter (current session)": "INC अनुमोदन पत्र (वर्तमान सत्र)",
    "HNRC recognition letter": "HNRC मान्यता पत्र",
    "UHSR affiliation letter": "UHSR संबद्धता पत्र",
    "Essentiality certificate / Govt. of Haryana NOC": "आवश्यकता प्रमाण पत्र / हरियाणा सरकार का अनापत्ति प्रमाण पत्र (NOC)",
    "Please send scanned copies of these letters (PDF) so they can be uploaded and linked here.": "कृपया इन पत्रों की स्कैन की हुई प्रतियाँ (PDF) भेजें, ताकि उन्हें यहाँ अपलोड और लिंक किया जा सके।",

    # ------------------------------------------------------------ HOSPITAL
    "Shri Ram College has its own <strong>100-bed hospital</strong>, where students gain supervised, hands-on clinical experience, an essential part of becoming a confident professional nurse or technologist.":
        "श्री राम कॉलेज का अपना <strong>100 बिस्तरों वाला अस्पताल</strong> है, जहाँ विद्यार्थी निगरानी में व्यावहारिक क्लिनिकल अनुभव प्राप्त करते हैं — जो एक आत्मविश्वासी पेशेवर नर्स या टेक्नोलॉजिस्ट बनने का ज़रूरी हिस्सा है।",
    "Attached hospital": "संबद्ध अस्पताल",
    "beds for supervised clinical practice on our own campus.": "बिस्तर, हमारे अपने परिसर में निगरानी में क्लिनिकल अभ्यास के लिए।",
    "On the wards": "वार्डों में",
    "Learning where care happens": "जहाँ सेवा होती है, वहीं सीखना",
    "From the early semesters, students move from skill labs to real patients under the guidance of nursing faculty and hospital staff, building confidence one posting at a time.":
        "शुरुआती सेमेस्टर से ही विद्यार्थी नर्सिंग शिक्षकों और अस्पताल कर्मचारियों के मार्गदर्शन में स्किल लैब से असली रोगियों तक पहुँचते हैं, और हर पोस्टिंग के साथ उनका आत्मविश्वास बढ़ता है।",
    "Clinical learning": "क्लिनिकल शिक्षण",
    "Bedside nursing care under qualified nursing faculty": "योग्य नर्सिंग शिक्षकों की देखरेख में रोगी के पास नर्सिंग देखभाल",
    "Rotations through medical, surgical, paediatric and maternity wards": "मेडिकल, सर्जिकल, बाल रोग और प्रसूति वार्डों में बारी-बारी से प्रशिक्षण",
    "Exposure to emergency, operation theatre and diagnostic services": "आपातकालीन, ऑपरेशन थिएटर और जाँच सेवाओं का अनुभव",
    "Case studies, care plans and clinical presentations": "केस स्टडी, केयर प्लान और क्लिनिकल प्रेज़ेंटेशन",
    "Community postings": "सामुदायिक पोस्टिंग",
    "Community health nursing in the villages around Digrota": "डिगरोता के आसपास के गाँवों में सामुदायिक स्वास्थ्य नर्सिंग",
    "Health surveys, immunisation and awareness drives": "स्वास्थ्य सर्वेक्षण, टीकाकरण और जागरूकता अभियान",
    "Maternal and child health outreach": "मातृ एवं शिशु स्वास्थ्य जनसंपर्क",
    "Health camps organised by the college": "कॉलेज द्वारा आयोजित स्वास्थ्य शिविर",
    "Departments &amp; services": "विभाग एवं सेवाएँ",
    "Please share the hospital's name, departments/specialities, number of doctors, and OPD timings, along with photographs.":
        "कृपया अस्पताल का नाम, विभाग/विशेषज्ञताएँ, डॉक्टरों की संख्या और ओपीडी का समय, फ़ोटो के साथ भेजें।",

    # ------------------------------------------------------------ FACILITIES
    "Our campus at Digrota is designed for focused study, practical training and a safe residential life.": "डिगरोता स्थित हमारा परिसर एकाग्र पढ़ाई, व्यावहारिक प्रशिक्षण और सुरक्षित आवासीय जीवन के लिए बनाया गया है।",
    "Please share photographs of the hostels, canteen, buses, auditorium and sports facilities, and the bus routes served.":
        "कृपया छात्रावास, कैंटीन, बसों, सभागार और खेल सुविधाओं के फ़ोटो, तथा बसों के मार्गों की जानकारी भेजें।",
    "Spacious, fully furnished lecture halls with comfortable seating and advanced teaching aids.": "आरामदायक बैठने की व्यवस्था और आधुनिक शिक्षण साधनों से युक्त बड़े, पूरी तरह सुसज्जित व्याख्यान कक्ष।",
    "Laboratories": "प्रयोगशालाएँ",
    "Labs with models, charts, specimens, microscopes and slides for anatomy, physiology and microbiology, plus nursing skill labs for practical training.":
        "एनाटॉमी, फ़िज़ियोलॉजी और माइक्रोबायोलॉजी के लिए मॉडल, चार्ट, नमूनों, माइक्रोस्कोप और स्लाइड से युक्त प्रयोगशालाएँ, साथ में व्यावहारिक प्रशिक्षण के लिए नर्सिंग स्किल लैब।",
    "Audio-visual lab": "ऑडियो-विज़ुअल लैब",
    "OHP, LCD projector, TV, posters, flannel boards, models and other teaching-learning material.": "ओएचपी, एलसीडी प्रोजेक्टर, टीवी, पोस्टर, फ़लालैन बोर्ड, मॉडल और अन्य शिक्षण सामग्री।",
    "Library": "पुस्तकालय",
    "A full library with 3,500+ medical and nursing books, 10 journals, Indian and international e-journals, newspapers and magazines.":
        "3,500+ चिकित्सा व नर्सिंग पुस्तकों, 10 जर्नल, भारतीय व अंतरराष्ट्रीय ई-जर्नल, समाचार पत्रों और पत्रिकाओं वाला पूर्ण पुस्तकालय।",
    "A venue for seminars, workshops, guest lectures and cultural events.": "सेमिनार, कार्यशालाओं, अतिथि व्याख्यानों और सांस्कृतिक कार्यक्रमों का स्थान।",
    "Hostels": "छात्रावास",
    "Separate hostels for girls and boys with mess facilities and security.": "मेस और सुरक्षा सहित छात्राओं और छात्रों के लिए अलग-अलग छात्रावास।",
    "Canteen": "कैंटीन",
    "A hygienic canteen serving meals and refreshments on campus.": "परिसर में भोजन और जलपान के लिए स्वच्छ कैंटीन।",
    "Transport": "परिवहन",
    "College buses connect the campus with nearby towns and villages.": "कॉलेज की बसें परिसर को आसपास के कस्बों और गाँवों से जोड़ती हैं।",
    "Wi-Fi campus": "वाई-फ़ाई परिसर",
    "Internet access for learning and research across the campus.": "पूरे परिसर में पढ़ाई और शोध के लिए इंटरनेट सुविधा।",
    "Gym &amp; sports": "जिम एवं खेल",
    "A gym and sports complex for fitness and recreation.": "फ़िटनेस और मनोरंजन के लिए जिम और खेल परिसर।",
    "Our own 100-bed hospital for clinical training.": "क्लिनिकल प्रशिक्षण के लिए हमारा अपना 100 बिस्तरों वाला अस्पताल।",
    "Medical care": "चिकित्सा सुविधा",
    "Medical facilities for students on campus.": "परिसर में विद्यार्थियों के लिए चिकित्सा सुविधाएँ।",
    "See the campus for yourself": "परिसर को स्वयं आकर देखें",
    "Visitors and parents are welcome. Contact the college office to plan a visit.": "आगंतुकों और अभिभावकों का स्वागत है। भ्रमण की योजना के लिए कॉलेज कार्यालय से संपर्क करें।",
    "Plan a visit": "भ्रमण की योजना बनाएँ",

    # ------------------------------------------------------------ FACULTY
    "Our teaching team of qualified nursing and medical faculty is led by the Principal, as required by Indian Nursing Council norms.":
        "भारतीय नर्सिंग परिषद के नियमों के अनुसार, योग्य नर्सिंग और चिकित्सा शिक्षकों की हमारी टीम का नेतृत्व प्रधानाचार्य करते हैं।",
    "Name": "नाम",
    "Designation": "पद",
    "Experience": "अनुभव",
    "Vice Principal": "उप-प्रधानाचार्य",
    "Professor / Associate Professor": "प्रोफ़ेसर / एसोसिएट प्रोफ़ेसर",
    "Assistant Professor / Tutor": "असिस्टेंट प्रोफ़ेसर / ट्यूटर",
    "Please share the faculty list (name, designation, qualification, experience, photo).": "कृपया शिक्षकों की सूची (नाम, पद, योग्यता, अनुभव, फ़ोटो) भेजें।",

    # ------------------------------------------------------------ GALLERY
    "A glimpse of life at Shri Ram College: the campus, our hospital and labs, and our students.": "श्री राम कॉलेज के जीवन की एक झलक: परिसर, हमारा अस्पताल और प्रयोगशालाएँ, और हमारे विद्यार्थी।",
    "Hospital &amp; laboratories": "अस्पताल एवं प्रयोगशालाएँ",
    "Student life": "विद्यार्थी जीवन",
    "Photos are from the college's Google Maps listing. Photos credited to other people were posted by visitors; get their permission (or replace them) before launch.":
        "ये फ़ोटो कॉलेज की गूगल मैप्स लिस्टिंग से लिए गए हैं। जिन फ़ोटो पर अन्य लोगों का नाम है, वे आगंतुकों ने पोस्ट किए थे; वेबसाइट शुरू करने से पहले उनकी अनुमति लें (या फ़ोटो बदलें)।",

    # ------------------------------------------------------------ CONTACT
    "Address": "पता",
    "Shri Ram College of Medical Science &amp; Research<br>VPO Digrota, Nangal Mala Road<br>Tehsil Satnali, Distt. Mahendragarh<br>Haryana – 123024":
        "श्री राम कॉलेज ऑफ़ मेडिकल साइंस एंड रिसर्च<br>गाँव व डाकघर डिगरोता, नांगल माला रोड<br>तहसील सतनाली, जिला महेंद्रगढ़<br>हरियाणा – 123024",
    '<a href="https://www.google.com/maps?q=28.365143,76.040255" target="_blank" rel="noopener">Open in Google Maps ↗</a>':
        '<a href="https://www.google.com/maps?q=28.365143,76.040255" target="_blank" rel="noopener">गूगल मैप्स में खोलें ↗</a>',
    "Phone &amp; email": "फ़ोन एवं ईमेल",
    'Phone: [sr_contact field="phone"]': 'फ़ोन: [sr_contact field="phone"]',
    'Mobile: <a href="tel:+918930132210">089301 32210</a>': 'मोबाइल: <a href="tel:+918930132210">089301 32210</a>',
    'Email: [sr_contact field="email"]': 'ईमेल: [sr_contact field="email"]',
    "Office hours: from 9:00 AM": "कार्यालय समय: सुबह 9:00 बजे से",
    "How to reach": "कैसे पहुँचें",
    "About 50 km by road from Mahendragarh town, via Satnali": "महेंद्रगढ़ शहर से सड़क मार्ग द्वारा लगभग 50 किमी, सतनाली होकर",
    "Nearest railway station: Nanwan (NWN)": "नज़दीकी रेलवे स्टेशन: नानवां (NWN)",
    "Nearest major airport: IGI Airport, New Delhi": "नज़दीकी बड़ा हवाई अड्डा: आईजीआई एयरपोर्ट, नई दिल्ली",
    "College buses available on nearby routes": "आसपास के मार्गों पर कॉलेज बसें उपलब्ध",
    "Map to Shri Ram College, Digrota": "श्री राम कॉलेज, डिगरोता का नक्शा",
    "Enquiry": "पूछताछ",
    "Send us an enquiry": "हमें पूछताछ भेजें",
    "Questions about admissions, courses, fees or hostels? Fill in the form and we will get back to you.": "प्रवेश, पाठ्यक्रम, शुल्क या छात्रावास के बारे में कोई प्रश्न? फ़ॉर्म भरें, हम आपसे संपर्क करेंगे।",

    # ------------------------------------------------------------ MANDATORY DISCLOSURE
    "Information disclosed in line with the requirements of the Indian Nursing Council and the affiliating university.": "भारतीय नर्सिंग परिषद और संबद्धता देने वाले विश्वविद्यालय की आवश्यकताओं के अनुसार प्रकट की गई जानकारी।",
    "Item": "मद",
    "Details": "विवरण",
    "Name of institution": "संस्थान का नाम",
    "Shri Ram College of Nursing / Shri Ram School of Nursing (Shri Ram College of Medical Science &amp; Research)":
        "श्री राम कॉलेज ऑफ़ नर्सिंग / श्री राम स्कूल ऑफ़ नर्सिंग (श्री राम कॉलेज ऑफ़ मेडिकल साइंस एंड रिसर्च)",
    "Year of establishment": "स्थापना वर्ष",
    "Courses &amp; intake": "पाठ्यक्रम एवं सीटें",
    "B.Sc Nursing (50), Post Basic B.Sc Nursing (40), B.Sc Paramedical Science (50), ANM (30), GNM (—)":
        "बी.एससी. नर्सिंग (50), पोस्ट बेसिक बी.एससी. नर्सिंग (40), बी.एससी. पैरामेडिकल साइंस (50), एएनएम (30), जीएनएम (—)",
    "Parent hospital": "मूल अस्पताल",
    '<a href="/fee-structure/">See Fee Structure</a>': '<a href="/fee-structure/">शुल्क संरचना देखें</a>',
    "Anti-ragging committee": "एंटी-रैगिंग समिति",
    "Grievance redressal / Internal complaints committee": "शिकायत निवारण / आंतरिक शिकायत समिति",
    "Please fill in the blank rows and send committee member lists, so this page meets the regulator's disclosure requirements.":
        "कृपया खाली पंक्तियाँ भरें और समितियों के सदस्यों की सूची भेजें, ताकि यह पृष्ठ नियामक की प्रकटीकरण आवश्यकताओं को पूरा करे।",

    # ------------------------------------------------------------ NOTICES
    "Admission notices, examination schedules, results and campus news.": "प्रवेश सूचनाएँ, परीक्षा कार्यक्रम, परिणाम और परिसर के समाचार।",
    "No notices have been published yet.": "अभी तक कोई सूचना प्रकाशित नहीं हुई है।",
}
